// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqgllwlrwlwdxhyhcbyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZ2xsd2xyd2x3ZHhoeWhjYnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzM2OTIsImV4cCI6MjA2ODkwOTY5Mn0.AO2AP3Jss5cDfMGSRk1C1AW8odZ81ZrqfDSXq8olYeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});